syntax keyword bubbleOperator and
syntax keyword bubbleOperator or
syntax keyword bubbleOperator not
syntax keyword bubbleKeyword continue
syntax keyword bubbleKeyword extern
syntax keyword bubbleKeyword export
syntax keyword bubbleBoolean true
syntax keyword bubbleBoolean false
syntax keyword bubbleType u8
syntax keyword bubbleType u16
syntax keyword bubbleType u32
syntax keyword bubbleType u64
syntax keyword bubbleType i8
syntax keyword bubbleType i16
syntax keyword bubbleType i32
syntax keyword bubbleType i64
syntax keyword bubbleType bool
syntax keyword bubbleType void
syntax keyword bubbleKeyword identifier
syntax keyword bubbleType string
syntax keyword bubbleKeyword int
syntax keyword bubbleKeyword float
syntax keyword bubbleKeyword ptr
syntax keyword bubbleKeyword addrof
syntax keyword bubbleKeyword deref
syntax keyword bubbleKeyword null
syntax keyword bubbleKeyword function
syntax keyword bubbleKeyword struct
syntax keyword bubbleConditionnal if
syntax keyword bubbleConditionnal else
syntax keyword bubbleKeyword for
syntax keyword bubbleKeyword while
syntax keyword bubbleKeyword return
syntax keyword bubbleKeyword let
syntax keyword bubbleKeyword import
syntax keyword bubbleKeyword from
syntax keyword bubbleKeyword break
syntax match bubblePunctuation "[(){},;:]"
syntax match bubbleOperator "="
syntax match bubbleOperator "+"
syntax match bubbleOperator "-"
syntax match bubbleOperator "*"
syntax match bubbleOperator "/"
syntax match bubbleOperator "%"
syntax match bubbleOperator "=="
syntax match bubbleOperator "!="
syntax match bubbleOperator "<"
syntax match bubbleOperator ">"
syntax match bubbleOperator "<="
syntax match bubbleOperator ">="
syntax match bubbleOperator "::"
syntax match bubblePunctuation "\."
syntax match bubbleFloat "\d\+\.\d*"
syntax match bubbleNumber "\d\+"
syntax match bubbleNumber "[+-]\d\+"
syntax match bubbleFunction /[a-z]\+[0-9a-zA-Z_]*\w*(/me=e-1
syntax region bubbleString start=+"+ end=+"+ skip=+\\"+
syntax region bubbleComment start=+//+ end=+\n+

" Hightlight groups
hi link bubbleKeyword Keyword
hi link bubbleOperator Operator
hi link bubbleConditionnal Conditional
hi link bubbleType Type
hi link bubblePunctuation @punctuation
hi link bubbleNumber Number
hi link bubbleBoolean Boolean
hi link bubbleFloat Float
hi link bubbleFunction Function
hi link bubbleString String
hi link bubbleComment Comment
