use self::lexer::{LexicalError, Token};

// We don't want to check this module because it's autogenerated by the build
// script. It's not actual part of the source code.
#[rustfmt::skip]
pub mod grammar;
pub mod lexer;

pub type StatementsParserResult<T> = Result<T, ParserError>;
pub type ParserError = lalrpop_util::ParseError<usize, Token, LexicalError>;
